### PR TITLE
Phil

### PR DESCRIPTION
**Pull request by PhillipOdd**
Initial pull request

### CODE REVIEW

**Comment by Isma1Huz** [comment]
- On your css files check the use of global names like "button" change them but giving them unique names .use classes or ids especially on the filter.css
- Remove the food.jpg below the app file and make sure it is in the assets folder
- The content you have in RecipeRoom should be in the Landing page.js and import landingpage component to RecipeRoom and render there.
-

**Review by Albert-Byrone — APPROVED** [review]
Kindly make  sure you have clear PR heading  not like Phil

**Comment by Albert-Byrone** [comment]
@Isma1Huz KIndly make sure the conflicts are resolved before merging the changes.

**Review by Isma1Huz — APPROVED** [review]
make the changes on the comment section

**Pull request merged**
